spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 121.41.82.252:8848
    gateway:
      routes:
        - id: test
          uri: http://www.baidu.com
          predicates:
              - Query=url,baidu
        - id: qq
          uri: http://www.qq.com
          predicates:
            - Query=url,qq